-- Divisions

insert into division (name) values ('Ayeyarwady Region');
insert into division (name) values ('Bago Region');
insert into division (name) values ('Chin State');
insert into division (name) values ('Kachin State');
insert into division (name) values ('Kayah State');
insert into division (name) values ('Kayin State');
insert into division (name) values ('Magway Region');
insert into division (name) values ('Mandalay Region');
insert into division (name) values ('Mon State');
insert into division (name) values ('Naypyidaw Union Territory');
insert into division (name) values ('Rakhine State');
insert into division (name) values ('Sagaing Region');
insert into division (name) values ('Shan State');
insert into division (name) values ('Tanintharyi Region');
insert into division (name) values ('Yangon Region');

-- Ayeyarwady Region

insert into township (division_id, name) values(1, 'Hinthada Township');
insert into township (division_id, name) values(1, 'Lemyethna Township');
insert into township (division_id, name) values(1, 'Zalun Township');
insert into township (division_id, name) values(1, 'Ithapyu Township');
insert into township (division_id, name) values(1, 'Labutta Township');
insert into township (division_id, name) values(1, 'Mawlamyinegyun Township');
insert into township (division_id, name) values(1, 'Kyonmanage Township');
insert into township (division_id, name) values(1, 'Pyinsalu Township');
insert into township (division_id, name) values(1, 'Danubyu Township');
insert into township (division_id, name) values(1, 'Ma-ubin Township');
insert into township (division_id, name) values(1, 'Nyaungdon Township');
insert into township (division_id, name) values(1, 'Pantanaw Township');
insert into township (division_id, name) values(1, 'Einme Township');
insert into township (division_id, name) values(1, 'Myaungmya Township');
insert into township (division_id, name) values(1, 'Wakema Township');
insert into township (division_id, name) values(1, 'Kangyidaunt Township');
insert into township (division_id, name) values(1, 'Kyaunggon Township');
insert into township (division_id, name) values(1, 'Kyonpyaw Township');
insert into township (division_id, name) values(1, 'Ngapudaw Township');
insert into township (division_id, name) values(1, 'Pathein Township');
insert into township (division_id, name) values(1, 'Thabaung Township');
insert into township (division_id, name) values(1, 'Yekyi Township');
insert into township (division_id, name) values(1, 'Bogale Township');
insert into township (division_id, name) values(1, 'Dedaye Township');
insert into township (division_id, name) values(1, 'Kyaiklat Township');
insert into township (division_id, name) values(1, 'Pyapon Township');
insert into township (division_id, name) values(1, 'Ahmar Township');
insert into township (division_id, name) values(1, 'Kyaunggon Township');
insert into township (division_id, name) values(1, 'Kyonpyaw Township');
insert into township (division_id, name) values(1, 'Yekyi Township');
insert into township (division_id, name) values(1, 'Ahtaung Township');
insert into township (division_id, name) values(1, 'Ngathinechaung Township');
insert into township (division_id, name) values(1, 'Ingapu Township');
insert into township (division_id, name) values(1, 'Kyangin Township');
insert into township (division_id, name) values(1, 'Myanaung Township');
insert into township (division_id, name) values(1, 'Kanaung Township');

-- Bago Region

insert into township (division_id, name) values (2, 'Bago Township');
insert into township (division_id, name) values (2, 'Daik-U Township');
insert into township (division_id, name) values (2, 'Kawa Township');
insert into township (division_id, name) values (2, 'Nyaunglebin Township');
insert into township (division_id, name) values (2, 'Shwegyin Township');
insert into township (division_id, name) values (2, 'Thanatpin Township');
insert into township (division_id, name) values (2, 'Waw Township');
insert into township (division_id, name) values (2, 'Kyauktaga Township');
insert into township (division_id, name) values (2, 'Kyaukkyi Township');
insert into township (division_id, name) values (2, 'Oktwin Township');
insert into township (division_id, name) values (2, 'Pyu Township');
insert into township (division_id, name) values (2, 'Tantabin Township');
insert into township (division_id, name) values (2, 'Taungoo Township');
insert into township (division_id, name) values (2, 'Yedashe Township');
insert into township (division_id, name) values (2, 'Pandaung Township');
insert into township (division_id, name) values (2, 'Paukkaung Township');
insert into township (division_id, name) values (2, 'Paungde Township');
insert into township (division_id, name) values (2, 'Pyay Township');
insert into township (division_id, name) values (2, 'Shwedaung Township');
insert into township (division_id, name) values (2, 'Thegon Township');
insert into township (division_id, name) values (2, 'Gyobingauk Township');
insert into township (division_id, name) values (2, 'Letpadan Township');
insert into township (division_id, name) values (2, 'Minhla Township');
insert into township (division_id, name) values (2, 'Monyo Township');
insert into township (division_id, name) values (2, 'Okpho Township');
insert into township (division_id, name) values (2, 'Tharrawaddy Township');
insert into township (division_id, name) values (2, 'Nattalin Township');
insert into township (division_id, name) values (2, 'Zigon Township');

-- Chin Division

insert into township (division_id, name) values (3, 'Falam Township');
insert into township (division_id, name) values (3, 'Tiddim Township');
insert into township (division_id, name) values (3, 'Ton Zang Township');
insert into township (division_id, name) values (3, 'Hakha Township');
insert into township (division_id, name) values (3, 'Htantlang Township');
insert into township (division_id, name) values (3, 'Matupi Township');
insert into township (division_id, name) values (3, 'Paletwa Township');
insert into township (division_id, name) values (3, 'Kanpetlet Township');
insert into township (division_id, name) values (3, 'Mindat Township');

-- Kachin Division

insert into township (division_id, name) values (4, 'Bhamo Township');
insert into township (division_id, name) values (4, 'Mansi Township');
insert into township (division_id, name) values (4, 'Momauk Township');
insert into township (division_id, name) values (4, 'Shwegu Township');
insert into township (division_id, name) values (4, 'Hpakant Township');
insert into township (division_id, name) values (4, 'Mogaung Township');
insert into township (division_id, name) values (4, 'Mohnyin Township');
insert into township (division_id, name) values (4, 'Chipwi Township');
insert into township (division_id, name) values (4, 'Hsawlaw Township');
insert into township (division_id, name) values (4, 'Injangyang Township');
insert into township (division_id, name) values (4, 'Myitkyina Township');
insert into township (division_id, name) values (4, 'Tanai Township');
insert into township (division_id, name) values (4, 'Waingmaw Township');
insert into township (division_id, name) values (4, 'Kawnglanghpu Township');
insert into township (division_id, name) values (4, 'Machanbaw Township');
insert into township (division_id, name) values (4, 'Nogmung Township');
insert into township (division_id, name) values (4, 'Putao Township');
insert into township (division_id, name) values (4, 'Sumprabum Township');

-- Kayah
insert into township (division_id, name) values (5, 'Bawlakhe Township');
insert into township (division_id, name) values (5, 'Hpasawng Township');
insert into township (division_id, name) values (5, 'Demoso Township');
insert into township (division_id, name) values (5, 'Hpruso Township');
insert into township (division_id, name) values (5, 'Loikaw Township');
insert into township (division_id, name) values (5, 'Shadaw Township');
insert into township (division_id, name) values (5, 'Mese Township');

-- Kayin State
insert into township (division_id, name) values (6, 'Hlaingbwe Township');
insert into township (division_id, name) values (6, 'Hpa-an Township');
insert into township (division_id, name) values (6, 'Thandaunggyi Township');
insert into township (division_id, name) values (6, 'Hpapun Township');
insert into township (division_id, name) values (6, 'Kawkareik Township');
insert into township (division_id, name) values (6, 'Kyain Seikgyi Township');
insert into township (division_id, name) values (6, 'Myawaddy Township');

-- Magway Region
insert into township (division_id, name) values (7, 'Gangaw Township');
insert into township (division_id, name) values (7, 'Saw Township');
insert into township (division_id, name) values (7, 'Htilin Township');
insert into township (division_id, name) values (7, 'Kyaukhtu Subtownship');
insert into township (division_id, name) values (7, 'Chauk Township');
insert into township (division_id, name) values (7, 'Magway Township');
insert into township (division_id, name) values (7, 'Myothit Township');
insert into township (division_id, name) values (7, 'Natmauk Township');
insert into township (division_id, name) values (7, 'Taungdwingyi Township');
insert into township (division_id, name) values (7, 'Yenangyaung Township');
insert into township (division_id, name) values (7, 'Minbu Township');
insert into township (division_id, name) values (7, 'Ngape Township');
insert into township (division_id, name) values (7, 'Pwintbyu Township');
insert into township (division_id, name) values (7, 'Salin Township');
insert into township (division_id, name) values (7, 'Sidoktaya Township');
insert into township (division_id, name) values (7, 'Myaing Township');
insert into township (division_id, name) values (7, 'Pakokku Township');
insert into township (division_id, name) values (7, 'Pauk Township');
insert into township (division_id, name) values (7, 'Seikphyu Township');
insert into township (division_id, name) values (7, 'Yesagyo Township');
insert into township (division_id, name) values (7, 'Aunglan Township');
insert into township (division_id, name) values (7, 'Kamma Township');
insert into township (division_id, name) values (7, 'Mindon Township');
insert into township (division_id, name) values (7, 'Minhla Township');
insert into township (division_id, name) values (7, 'Sinbaungwe Township');
insert into township (division_id, name) values (7, 'Thayet Township');

-- Mandalay Region
insert into township (division_id, name) values (8, 'Kyaukse Township');
insert into township (division_id, name) values (8, 'Myittha Township');
insert into township (division_id, name) values (8, 'Sintgaing Township');
insert into township (division_id, name) values (8, 'Tada-U Township');
insert into township (division_id, name) values (8, 'Amarapura Township');
insert into township (division_id, name) values (8, 'Aungmyethazan Township');
insert into township (division_id, name) values (8, 'Chanayethazan Township');
insert into township (division_id, name) values (8, 'Chanmyathazi Township');
insert into township (division_id, name) values (8, 'Maha Aungmye Township');
insert into township (division_id, name) values (8, 'Patheingyi Township');
insert into township (division_id, name) values (8, 'Pyigyidagun Township');
insert into township (division_id, name) values (8, 'Mahlaing Township');
insert into township (division_id, name) values (8, 'Meiktila Township');
insert into township (division_id, name) values (8, 'Thazi Township');
insert into township (division_id, name) values (8, 'Wundwin Township');
insert into township (division_id, name) values (8, 'Myingyan Township');
insert into township (division_id, name) values (8, 'Natogyi Township');
insert into township (division_id, name) values (8, 'Ngazun Township');
insert into township (division_id, name) values (8, 'Taungtha Township');
insert into township (division_id, name) values (8, 'Kyaukpadaung Township');
insert into township (division_id, name) values (8, 'Nyaung-U Township');
insert into township (division_id, name) values (8, 'Madaya Township');
insert into township (division_id, name) values (8, 'Mogok Township');
insert into township (division_id, name) values (8, 'Pyinoolwin Township');
insert into township (division_id, name) values (8, 'Singu Township');
insert into township (division_id, name) values (8, 'Thabeikkyin Township');
insert into township (division_id, name) values (8, 'Pyawbwe Township');
insert into township (division_id, name) values (8, 'Yamethin Township');

-- Mon State
insert into township (division_id, name) values (9, 'Chaungzon Township');
insert into township (division_id, name) values (9, 'Kyaikmaraw Township');
insert into township (division_id, name) values (9, 'Mawlamyine Township');
insert into township (division_id, name) values (9, 'Mudon Township');
insert into township (division_id, name) values (9, 'Thanbyuzayat Township');
insert into township (division_id, name) values (9, 'Ye Township');
insert into township (division_id, name) values (9, 'Bilin Township');
insert into township (division_id, name) values (9, 'Kyaikto Township');
insert into township (division_id, name) values (9, 'Paung Township');
insert into township (division_id, name) values (9, 'Thaton Township');

-- Naypyidaw Union Territory
insert into township (division_id, name) values (10, 'Ottarathiri Township');
insert into township (division_id, name) values (10, 'Pobbathiri Township');
insert into township (division_id, name) values (10, 'Tatkon Township');
insert into township (division_id, name) values (10, 'Zeyarthiri Township');
insert into township (division_id, name) values (10, 'Dekkhinathiri Township');
insert into township (division_id, name) values (10, 'Lewe Township');
insert into township (division_id, name) values (10, 'Pyinmana Township');
insert into township (division_id, name) values (10, 'Zabuthiri Township');

-- Rakhine State
insert into township (division_id, name) values (11, 'Ann Township');
insert into township (division_id, name) values (11, 'Kyaukpyu Township');
insert into township (division_id, name) values (11, 'Manaung Township');
insert into township (division_id, name) values (11, 'Ramree Township');
insert into township (division_id, name) values (11, 'Buthidaung Township');
insert into township (division_id, name) values (11, 'Maungdaw Township');
insert into township (division_id, name) values (11, 'Pauktaw Township');
insert into township (division_id, name) values (11, 'Ponnagyun Township');
insert into township (division_id, name) values (11, 'Rathedaung Township');
insert into township (division_id, name) values (11, 'Sittwe Township');
insert into township (division_id, name) values (11, 'Thandwe Township');
insert into township (division_id, name) values (11, 'Toungup Township');
insert into township (division_id, name) values (11, 'Gwa Township');
insert into township (division_id, name) values (11, 'Maei Subtownship');
insert into township (division_id, name) values (11, 'Kyeintali Subtownship');
insert into township (division_id, name) values (11, 'Kyauktaw Township');
insert into township (division_id, name) values (11, 'Minbya Township');
insert into township (division_id, name) values (11, 'Mrauk-U Township');
insert into township (division_id, name) values (11, 'Myebon Township');

-- Sagaing
insert into township (division_id, name) values (12, 'Hkamti Township');
insert into township (division_id, name) values (12, 'Homalin Township');
insert into township (division_id, name) values (12, 'Kanbalu Township');
insert into township (division_id, name) values (12, 'Kyunhla Township');
insert into township (division_id, name) values (12, 'Kale Township');
insert into township (division_id, name) values (12, 'Kalewa Township');
insert into township (division_id, name) values (12, 'Mingin Township');
insert into township (division_id, name) values (12, 'Banmauk Township');
insert into township (division_id, name) values (12, 'Indaw Township');
insert into township (division_id, name) values (12, 'Katha Township');
insert into township (division_id, name) values (12, 'Htigyaing Township');
insert into township (division_id, name) values (12, 'Mawlaik Township');
insert into township (division_id, name) values (12, 'Paungbyin Township');
insert into township (division_id, name) values (12, 'Ayadaw Township');
insert into township (division_id, name) values (12, 'Budalin Township');
insert into township (division_id, name) values (12, 'Chaung-U Township');
insert into township (division_id, name) values (12, 'Monywa Township');
insert into township (division_id, name) values (12, 'Myaung Township');
insert into township (division_id, name) values (12, 'Myinmu Township');
insert into township (division_id, name) values (12, 'Sagaing Township');
insert into township (division_id, name) values (12, 'Khin-U Township');
insert into township (division_id, name) values (12, 'Shwebo Township');
insert into township (division_id, name) values (12, 'Wetlet Township');
insert into township (division_id, name) values (12, 'Tabayin Township');
insert into township (division_id, name) values (12, 'Taze Township');
insert into township (division_id, name) values (12, 'Ye-U Township');
insert into township (division_id, name) values (12, 'Tamu Township');
insert into township (division_id, name) values (12, 'Kani Township');
insert into township (division_id, name) values (12, 'Pale Township');
insert into township (division_id, name) values (12, 'Salingyi Township');
insert into township (division_id, name) values (12, 'Yinmabin Township');
insert into township (division_id, name) values (12, 'Kawlin Township');
insert into township (division_id, name) values (12, 'Pinlebu Township');
insert into township (division_id, name) values (12, 'Wuntho Township');
insert into township (division_id, name) values (12, 'Lahe Township');
insert into township (division_id, name) values (12, 'Leshi Township');
insert into township (division_id, name) values (12, 'Nanyun Township');

-- Shan
insert into township (division_id, name) values (13, 'Kengtung Township');
insert into township (division_id, name) values (13, 'Mong Khet Township');
insert into township (division_id, name) values (13, 'Mong La Township (SR4)');
insert into township (division_id, name) values (13, 'Mong Yang Township');
insert into township (division_id, name) values (13, 'Mine Pauk Subtownship');
insert into township (division_id, name) values (13, 'Minelar Subtownship');
insert into township (division_id, name) values (13, 'Mong Hpayak Township (SR4)');
insert into township (division_id, name) values (13, 'Mong Yawng Township');
insert into township (division_id, name) values (13, 'Mineyu Subtownship');
insert into township (division_id, name) values (13, 'Mong Hsat Township');
insert into township (division_id, name) values (13, 'Mong Ping Township');
insert into township (division_id, name) values (13, 'Mong Tong Township');
insert into township (division_id, name) values (13, 'Minekoke Subtownship');
insert into township (division_id, name) values (13, 'Monehta Subtownship');
insert into township (division_id, name) values (13, 'Ponparkyin Subtownship');
insert into township (division_id, name) values (13, 'Tontar Subtownship');
insert into township (division_id, name) values (13, 'Tachileik Township');
insert into township (division_id, name) values (13, 'Kyaing Lap Subtownship (Kenglap)');
insert into township (division_id, name) values (13, 'Talay Subtownship');
insert into township (division_id, name) values (13, 'Kunlong Township');
insert into township (division_id, name) values (13, 'Hsipaw Township');
insert into township (division_id, name) values (13, 'Kyaukme Township');
insert into township (division_id, name) values (13, 'Namtu Township');
insert into township (division_id, name) values (13, 'Nawnghkio Township');
insert into township (division_id, name) values (13, 'Minelon Subtownship');
insert into township (division_id, name) values (13, 'Minengaw Subtownship');
insert into township (division_id, name) values (13, 'Hseni Township');
insert into township (division_id, name) values (13, 'Lashio Township');
insert into township (division_id, name) values (13, 'Mongyai Township');
insert into township (division_id, name) values (13, 'Tangyan Township');
insert into township (division_id, name) values (13, 'Kutkai Township');
insert into township (division_id, name) values (13, 'Mu Se Township');
insert into township (division_id, name) values (13, 'Nanhkan Township');
insert into township (division_id, name) values (13, 'Manhero Subtownship');
insert into township (division_id, name) values (13, 'Monekoe Subtownship');
insert into township (division_id, name) values (13, 'Pansai Subtownship (Kyu-kok)');
insert into township (division_id, name) values (13, 'Tamoenye Subtownship');
insert into township (division_id, name) values (13, 'Mabein Township');
insert into township (division_id, name) values (13, 'Mongmit Township');
insert into township (division_id, name) values (13, 'Langhko Township');
insert into township (division_id, name) values (13, 'Mawkmai Township');
insert into township (division_id, name) values (13, 'Mong Nai Township');
insert into township (division_id, name) values (13, 'Mong Pan Township');
insert into township (division_id, name) values (13, 'Homane Subtownship');
insert into township (division_id, name) values (13, 'Kengtaung Subtownship');
insert into township (division_id, name) values (13, 'Kunhing Township');
insert into township (division_id, name) values (13, 'Kyethi Township');
insert into township (division_id, name) values (13, 'Lai-Hka Township');
insert into township (division_id, name) values (13, 'Loilen Township');
insert into township (division_id, name) values (13, 'Mong Hsu Township');
insert into township (division_id, name) values (13, 'Mong Kung Township');
insert into township (division_id, name) values (13, 'Nansang Township');
insert into township (division_id, name) values (13, 'Karli Subtownship');
insert into township (division_id, name) values (13, 'Kholan Subtownship');
insert into township (division_id, name) values (13, 'Minenaung Subtownship');
insert into township (division_id, name) values (13, 'Minesan Subtownship');
insert into township (division_id, name) values (13, 'Panglong Subtownship');
insert into township (division_id, name) values (13, 'Kalaw Township');
insert into township (division_id, name) values (13, 'Lawksawk Township');
insert into township (division_id, name) values (13, 'Nyaungshwe Township');
insert into township (division_id, name) values (13, 'Pekon Township');
insert into township (division_id, name) values (13, 'Taunggyi Township');
insert into township (division_id, name) values (13, 'Indaw Subtownship');
insert into township (division_id, name) values (13, 'Kyauktalongyi Subtownship');
insert into township (division_id, name) values (13, 'Naungtayar Subtownship');

-- Tanintharyi
insert into township (division_id, name) values (14, 'Dawei Township');
insert into township (division_id, name) values (14, 'Launglon Township');
insert into township (division_id, name) values (14, 'Thayetchaung Township');
insert into township (division_id, name) values (14, 'Yebyu Township');
insert into township (division_id, name) values (14, 'Kaleinaung Subtownship');
insert into township (division_id, name) values (14, 'Myitta Subtownship');
insert into township (division_id, name) values (14, 'Bokepyin Township');
insert into township (division_id, name) values (14, 'Kawthaung Township');
insert into township (division_id, name) values (14, 'Karathuri Subtownship');
insert into township (division_id, name) values (14, 'Khamaukgyi Subtownship');
insert into township (division_id, name) values (14, 'Pyigyimandaing Subtownship');
insert into township (division_id, name) values (14, 'Kyunsu Township');
insert into township (division_id, name) values (14, 'Myeik Township');
insert into township (division_id, name) values (14, 'Palaw Township');
insert into township (division_id, name) values (14, 'Tanintharyi Township');
insert into township (division_id, name) values (14, 'Palauk Subtownship');

-- Yangon
insert into township (division_id, name) values (15, 'Botataung Township');
insert into township (division_id, name) values (15, 'Dagon Seikkan Township');
insert into township (division_id, name) values (15, 'East Dagon Township');
insert into township (division_id, name) values (15, 'North Dagon Township');
insert into township (division_id, name) values (15, 'North Okkalapa Township');
insert into township (division_id, name) values (15, 'Pazundaung Township');
insert into township (division_id, name) values (15, 'South Dagon Township');
insert into township (division_id, name) values (15, 'South Okkalapa Township');
insert into township (division_id, name) values (15, 'Thingangyun Township');
insert into township (division_id, name) values (15, 'Dawbon Township1');
insert into township (division_id, name) values (15, 'Mingala Taungnyunt Township1');
insert into township (division_id, name) values (15, 'Tamwe Township1');
insert into township (division_id, name) values (15, 'Thaketa Township1');
insert into township (division_id, name) values (15, 'Yankin Township1');
insert into township (division_id, name) values (15, 'Hlaingthaya Township');
insert into township (division_id, name) values (15, 'Insein Township');
insert into township (division_id, name) values (15, 'Mingaladon Township');
insert into township (division_id, name) values (15, 'Shwepyitha Township');
insert into township (division_id, name) values (15, 'Hlegu Township');
insert into township (division_id, name) values (15, 'Hmawbi Township');
insert into township (division_id, name) values (15, 'Htantabin Township');
insert into township (division_id, name) values (15, 'Taikkyi Township');
insert into township (division_id, name) values (15, 'Dala Township');
insert into township (division_id, name) values (15, 'Seikkyi Kanaungto Township');
insert into township (division_id, name) values (15, 'Cocokyun Township');
insert into township (division_id, name) values (15, 'Kawhmu Township');
insert into township (division_id, name) values (15, 'Kayan Township');
insert into township (division_id, name) values (15, 'Kungyangon Township');
insert into township (division_id, name) values (15, 'Kyauktan Township');
insert into township (division_id, name) values (15, 'Thanlyin Township');
insert into township (division_id, name) values (15, 'Thongwa Township');
insert into township (division_id, name) values (15, 'Twante Township');
insert into township (division_id, name) values (15, 'Tada Subtownship');
insert into township (division_id, name) values (15, 'Ahlon Township');
insert into township (division_id, name) values (15, 'Bahan Township');
insert into township (division_id, name) values (15, 'Dagon Township');
insert into township (division_id, name) values (15, 'Kyauktada Township');
insert into township (division_id, name) values (15, 'Kyimyindaing Township');
insert into township (division_id, name) values (15, 'Lanmadaw Township');
insert into township (division_id, name) values (15, 'Latha Township');
insert into township (division_id, name) values (15, 'Pabedan Township');
insert into township (division_id, name) values (15, 'Sanchaung Township');
insert into township (division_id, name) values (15, 'Seikkan Township');
insert into township (division_id, name) values (15, 'Hlaing Township');
insert into township (division_id, name) values (15, 'Kamayut Township');
insert into township (division_id, name) values (15, 'Mayangon Township');
